import { DEFAULT_PROFILE_IMAGE } from "./config";

export const state = {
  dashboard: {
    saldoActual: 0,
    gastos: [],
    ahorros: [],
    selectedAhorroId: null,
    formData: {
      descripcion: "",
      monto: "",
      categoria: "Comida",
    },
    ingresoForm: {
      monto: "",
      concepto: "",
      origen: "Sueldo",
    },
    nuevoAhorroForm: {
      nombre: "",
      montoInicial: "",
      meta: "",
    },
    destinoForm: {
      monto: "",
    },
    ahorroDestinoId: null,
    showAllRecentExpenses: false,
    modals: {
      ingreso: false,
      ahorro: false,
      destino: false,
    },
  },
  finanzas: {
    currentPeriod: "",
    monthlyIncome: 0,
    monthlySavingsGoal: 0,
    categories: [
      "Supermercado",
      "Transporte",
      "Entretenimiento",
      "Salud",
      "Restaurantes",
      "Servicios",
      "Otros",
    ],
    ingresoCategories: ["Transferencia", "Prestamo", "Bono", "Venta"],
    ticketGoalByPeriod: {},
    tags: [],
    gastos: [],
    cargar: {
      activeTab: "gasto",
      ticketFileName: "",
      ocrLoading: false,
      form: {
        comercio: "",
        fecha: "",
        monto: "",
        categoria: "",
        descripcion: "",
        selectedTagIds: [],
      },
      ingresoForm: {
        fecha: "",
        monto: "",
        categoria: "",
        descripcion: "",
      },
      batchTickets: [],
      batchMode: false,
    },
    filtros: {
      search: "",
      categoria: "Todas",
      periodo: "",
      tipo: "Todos",
      fechaDesde: "",
      fechaHasta: "",
      etiqueta: null,
    },
    ui: {
      editingExpenseId: null,
      deletingExpenseId: null,
      editingAhorroId: null,
      deletingAhorroId: null,
      depositandoAhorroId: null,
      retirhandoAhorroId: null,
      budgetViewPeriod: "",
      editingBudgetId: null,
    },
    recomendaciones: [],
    budgets: [],
    customCategories: [],
  },
  asesor: {
    clientes: [],
    busqueda: "",
    orden: "a-z",
    clienteSeleccionadoId: null,
    nuevoCliente: {
      nombre: "",
      codigo: "",
    },
    modals: {
      nuevoCliente: false,
    },
  },
  detalleCliente: {
    gastos: [],
    recomendaciones: [],
    gastosPorMes: [],
    graficoCategorias: {
      porcentaje: 0,
      categorias: [],
    },
    nuevaRecomendacionTitulo: "",
    nuevaRecomendacionTexto: "",
    showAllRecentExpenses: false,
  },
  perfil: {
    id: null,
    nombre: "",
    email: "",
    imagen: DEFAULT_PROFILE_IMAGE,
    passwordData: {
      actual: "",
      nueva: "",
      confirmar: "",
    },
    imagePreview: DEFAULT_PROFILE_IMAGE,
  },
  currentUser: null,
  profileLoaded: false,
  authRecovery: {
    email: "",
    code: "",
    codeVerified: false,
  },
  authRegistration: {
    email: "",
    codeVerified: false,
  },
  configuracion: {
    moneda: "ARS",
    idioma: "es",
    tema: "system",
    temaOscuro: false,
    tamanioFuente: "md",
    densidad: "comfortable",
    reducirAnimaciones: false,
    mostrarCentavos: false,
    autenticacionDos: false,
    sesionesActivas: true,
    sesiones: [],
    perfilFinanciero: {
      ingresoEstimado: "",
      objetivoAhorro: "",
    },
    asesoria: {
      asesor: null,
      solicitud: {
        nombre: "",
        email: "",
        especialidad: "",
      },
    },
  },
  notificaciones: {
    resumenSemanal: true,
    alertaPago: true,
    alertaPresupuesto: true,
    movimientosGrandes: true,
    recomendacionesIA: true,
  },
};
