import { DEFAULT_PROFILE_IMAGE } from "./config";

export const state = {
  dashboard: {
    saldoActual: 6149.25,
    gastos: [
      {
        id: "1",
        descripcion: "Almuerzo",
        monto: 25.5,
        categoria: "Comida",
        fecha: "24 mar",
      },
      {
        id: "2",
        descripcion: "Gasolina",
        monto: 45,
        categoria: "Transporte",
        fecha: "23 mar",
      },
      {
        id: "3",
        descripcion: "Alquiler",
        monto: 1200,
        categoria: "Vivienda",
        fecha: "20 mar",
      },
    ],
    ahorros: [
      { id: "1", nombre: "Vacaciones", monto: 1500, meta: 3000 },
      { id: "2", nombre: "Auto Nuevo", monto: 850, meta: 2500 },
      { id: "3", nombre: "Emergencias", monto: 2000 },
    ],
    formData: {
      descripcion: "",
      monto: "",
      categoria: "Comida",
    },
    ingresoForm: {
      monto: "",
      concepto: "",
      origen: "Sueldo",
    },
    nuevoAhorroForm: {
      nombre: "",
      montoInicial: "",
      meta: "",
    },
    destinoForm: {
      monto: "",
    },
    ahorroDestinoId: null,
    showAllRecentExpenses: false,
    modals: {
      ingreso: false,
      ahorro: false,
      destino: false,
    },
  },
  finanzas: {
    currentPeriod: "2026-04",
    monthlyIncome: 0,
    monthlySavingsGoal: 0,
    categories: [
      "Supermercado",
      "Transporte",
      "Entretenimiento",
      "Salud",
      "Restaurantes",
      "Servicios",
      "Otros",
    ],
    ticketGoalByPeriod: {
      "2026-04": 34,
    },
    gastos: [
      {
        id: "g-1",
        comercio: "Disco Supermaxi",
        categoria: "Supermercado",
        descripcion: "Compras semanales",
        fecha: "2026-04-18",
        monto: 42480,
      },
      {
        id: "g-2",
        comercio: "SUBE recarga",
        categoria: "Transporte",
        descripcion: "Recarga semanal",
        fecha: "2026-04-17",
        monto: 6200,
      },
      {
        id: "g-3",
        comercio: "Netflix",
        categoria: "Entretenimiento",
        descripcion: "Suscripcion mensual",
        fecha: "2026-04-16",
        monto: 8999,
      },
      {
        id: "g-4",
        comercio: "YPF",
        categoria: "Transporte",
        descripcion: "Combustible",
        fecha: "2026-04-15",
        monto: 38750,
      },
      {
        id: "g-5",
        comercio: "Farmacity",
        categoria: "Salud",
        descripcion: "Medicamentos",
        fecha: "2026-04-14",
        monto: 10340,
      },
      {
        id: "g-6",
        comercio: "McDonalds",
        categoria: "Restaurantes",
        descripcion: "Almuerzo",
        fecha: "2026-04-13",
        monto: 7800,
      },
      {
        id: "g-7",
        comercio: "Alquiler temporal",
        categoria: "Servicios",
        descripcion: "Ajuste mensual",
        fecha: "2026-04-03",
        monto: 33000,
      },
      {
        id: "g-8",
        comercio: "Carrefour",
        categoria: "Supermercado",
        descripcion: "Compra quincenal",
        fecha: "2026-03-25",
        monto: 63240,
      },
      {
        id: "g-9",
        comercio: "YPF",
        categoria: "Transporte",
        descripcion: "Combustible",
        fecha: "2026-03-12",
        monto: 9800,
      },
      {
        id: "g-10",
        comercio: "Cablevision",
        categoria: "Servicios",
        descripcion: "Internet y cable",
        fecha: "2026-03-08",
        monto: 16200,
      },
      {
        id: "g-11",
        comercio: "Cinepolis",
        categoria: "Entretenimiento",
        descripcion: "Entradas",
        fecha: "2026-03-05",
        monto: 8600,
      },
      {
        id: "g-12",
        comercio: "Sushi Club",
        categoria: "Restaurantes",
        descripcion: "Cena fin de semana",
        fecha: "2026-03-02",
        monto: 10900,
      },
      {
        id: "g-13",
        comercio: "Coto",
        categoria: "Supermercado",
        descripcion: "Compra mensual",
        fecha: "2026-02-20",
        monto: 54800,
      },
      {
        id: "g-14",
        comercio: "SUBE recarga",
        categoria: "Transporte",
        descripcion: "Recarga mensual",
        fecha: "2026-02-11",
        monto: 4500,
      },
      {
        id: "g-15",
        comercio: "YPF",
        categoria: "Transporte",
        descripcion: "Combustible",
        fecha: "2026-02-04",
        monto: 6200,
      },
      {
        id: "g-16",
        comercio: "Spotify",
        categoria: "Entretenimiento",
        descripcion: "Plan familiar",
        fecha: "2026-02-03",
        monto: 3200,
      },
      {
        id: "g-17",
        comercio: "AySA",
        categoria: "Servicios",
        descripcion: "Factura de agua",
        fecha: "2026-02-01",
        monto: 8700,
      },
      {
        id: "g-18",
        comercio: "Coto",
        categoria: "Supermercado",
        descripcion: "Compra mensual",
        fecha: "2026-01-21",
        monto: 51200,
      },
      {
        id: "g-19",
        comercio: "Personal",
        categoria: "Servicios",
        descripcion: "Plan movil",
        fecha: "2026-01-11",
        monto: 11800,
      },
      {
        id: "g-20",
        comercio: "YPF",
        categoria: "Transporte",
        descripcion: "Combustible",
        fecha: "2026-01-08",
        monto: 6300,
      },
      {
        id: "g-21",
        comercio: "Burger House",
        categoria: "Restaurantes",
        descripcion: "Cena",
        fecha: "2026-01-05",
        monto: 9800,
      },
      {
        id: "g-22",
        comercio: "Cinepolis",
        categoria: "Entretenimiento",
        descripcion: "Estreno",
        fecha: "2026-01-03",
        monto: 7400,
      },
      {
        id: "g-23",
        comercio: "Coto",
        categoria: "Supermercado",
        descripcion: "Compra mensual",
        fecha: "2025-12-18",
        monto: 46800,
      },
      {
        id: "g-24",
        comercio: "SUBE recarga",
        categoria: "Transporte",
        descripcion: "Recarga mensual",
        fecha: "2025-12-17",
        monto: 4200,
      },
      {
        id: "g-25",
        comercio: "YPF",
        categoria: "Transporte",
        descripcion: "Combustible",
        fecha: "2025-12-10",
        monto: 6100,
      },
      {
        id: "g-26",
        comercio: "Medifarma",
        categoria: "Salud",
        descripcion: "Consulta y medicamentos",
        fecha: "2025-12-06",
        monto: 8300,
      },
      {
        id: "g-27",
        comercio: "Fibertel",
        categoria: "Servicios",
        descripcion: "Internet",
        fecha: "2025-12-04",
        monto: 9800,
      },
      {
        id: "g-28",
        comercio: "Coto",
        categoria: "Supermercado",
        descripcion: "Compra mensual",
        fecha: "2025-11-18",
        monto: 42000,
      },
      {
        id: "g-29",
        comercio: "Spotify",
        categoria: "Entretenimiento",
        descripcion: "Plan premium",
        fecha: "2025-11-11",
        monto: 1999,
      },
      {
        id: "g-30",
        comercio: "YPF",
        categoria: "Transporte",
        descripcion: "Combustible",
        fecha: "2025-11-07",
        monto: 5800,
      },
      {
        id: "g-31",
        comercio: "Edenor",
        categoria: "Servicios",
        descripcion: "Factura de luz",
        fecha: "2025-11-03",
        monto: 12200,
      },
      {
        id: "g-32",
        comercio: "Cinepolis",
        categoria: "Entretenimiento",
        descripcion: "Entradas",
        fecha: "2025-11-01",
        monto: 6100,
      },
    ],
    cargar: {
      ticketFileName: "",
      ocrLoading: false,
      form: {
        comercio: "",
        fecha: "",
        monto: "",
        categoria: "",
        descripcion: "",
      },
    },
    filtros: {
      search: "",
      categoria: "Todas",
      periodo: "2026-04",
    },
    ui: {
      editingExpenseId: null,
      deletingExpenseId: null,
    },
    recomendaciones: [
      {
        id: "r-1",
        severity: "danger",
        title: "Gasto excesivo en combustible",
        source: "asesor",
        body: "Tu gasto en combustible este mes fue 3.2x mayor que tu promedio historico. Revisa si hubo un viaje extraordinario o una ineficiencia de consumo.",
        date: "2026-04",
        category: "Transporte",
      },
      {
        id: "r-2",
        severity: "warning",
        title: "Entretenimiento cerca del limite",
        source: "asesor",
        body: "Ya consumiste el 82% del presupuesto mensual de entretenimiento en la primera quincena.",
        date: "2026-04",
        category: "Entretenimiento",
      },
      {
        id: "r-3",
        severity: "good",
        title: "Excelente control en salud",
        source: "asesor",
        body: "Tus gastos de salud se mantienen estables por tercer mes consecutivo y dentro del presupuesto estimado.",
        date: "2026-03",
        category: "Salud",
      },
      {
        id: "r-4",
        severity: "info",
        title: "Sugerencia de ahorro en restaurantes",
        source: "ia",
        body: "Si reduces un 10% tus gastos en restaurantes, podrias ahorrar alrededor de 4800 por mes adicional.",
        date: "2026-04",
        category: "Habitos",
      },
      {
        id: "r-5",
        severity: "warning",
        title: "Presupuesto de suscripciones superado",
        source: "ia",
        body: "Detectamos 5 suscripciones activas que no estás usando. Podrías ahorrar 2500 mensuales cancelándolas.",
        date: "2026-04",
        category: "Entretenimiento",
      },
      {
        id: "r-6",
        severity: "info",
        title: "Aumento en gastos de servicios",
        source: "asesor",
        body: "Los servicios (agua, luz, internet) aumentaron 15% respecto al mes anterior. Verifica el consumo en detalle.",
        date: "2026-05",
        category: "Servicios",
      },
      {
        id: "r-7",
        severity: "good",
        title: "Meta de ahorro alcanzada",
        source: "ia",
        body: "Felicitaciones! Alcanzaste tu meta de ahorro del 20% del ingreso mensual. Continua así!",
        date: "2026-05",
        category: "Ahorros",
      },
      {
        id: "r-8",
        severity: "danger",
        title: "Gasto atípico detectado",
        source: "asesor",
        body: "Se detectó una compra de 45000 en electrónica. ¿Es una compra planificada o debería revisarse?",
        date: "2026-03",
        category: "Electrónica",
      },
      {
        id: "r-9",
        severity: "warning",
        title: "Tendencia de gastos en alimentos",
        source: "ia",
        body: "Los gastos en alimentos han incrementado un 12% en los últimos 3 meses. Considera revisar hábitos de compra.",
        date: "2026-02",
        category: "Alimentos",
      },
      {
        id: "r-10",
        severity: "info",
        title: "Nuevo ahorro potencial identificado",
        source: "asesor",
        body: "Refinanciando tu deuda de tarjeta, podrías ahorrar 800 mensuales en intereses. ¿Te interesa cotizar?",
        date: "2026-03",
        category: "Deudas",
      },
      {
        id: "r-11",
        severity: "good",
        title: "Reducción exitosa en transporte",
        source: "ia",
        body: "Excelente trabajo! Redujiste los gastos de transporte en un 25% respecto a enero.",
        date: "2026-02",
        category: "Transporte",
      },
      {
        id: "r-12",
        severity: "warning",
        title: "Presupuesto de viajes pendiente",
        source: "asesor",
        body: "Planificaremos tu viaje a Cartagena. ¿Cuál es tu presupuesto máximo y fechas tentativas?",
        date: "2026-01",
        category: "Viajes",
      },
    ],
  },
  asesor: {
    clientes: [
      {
        id: "1",
        nombre: "Martin Garcia",
        gastosMes: 180200,
        ahorros: 2500,
        presupuesto: 200000,
        estado: "normal",
        tickets: 34,
      },
      {
        id: "2",
        nombre: "Ana Lopez",
        gastosMes: 89400,
        ahorros: 5200,
        presupuesto: 180000,
        estado: "bueno",
        tickets: 21,
      },
      {
        id: "3",
        nombre: "Carlos Perez",
        gastosMes: 312800,
        ahorros: 1800,
        presupuesto: 260000,
        estado: "alerta",
        tickets: 58,
      },
      {
        id: "4",
        nombre: "Lucia Ramirez",
        gastosMes: 104100,
        ahorros: 4100,
        presupuesto: 190000,
        estado: "bueno",
        tickets: 29,
      },
    ],
    busqueda: "",
    orden: "a-z",
    clienteSeleccionadoId: null,
    nuevoCliente: {
      nombre: "",
      codigo: "",
    },
    modals: {
      nuevoCliente: false,
    },
  },
  detalleCliente: {
    gastos: [
      { id: "1", descripcion: "Almuerzo",     monto: 25.5,  categoria: "Comida",      fecha: "24 mar" },
      { id: "2", descripcion: "Gasolina",     monto: 45,    categoria: "Transporte",  fecha: "23 mar" },
      { id: "3", descripcion: "Alquiler",     monto: 1200,  categoria: "Vivienda",    fecha: "20 mar" },
      { id: "4", descripcion: "Internet",     monto: 50,    categoria: "Servicios",   fecha: "18 mar" },
      { id: "5", descripcion: "Supermercado", monto: 150,   categoria: "Comida",      fecha: "17 mar" },
      { id: "6", descripcion: "Cine",         monto: 30,    categoria: "Ocio",        fecha: "15 mar" },
      { id: "7", descripcion: "Farmacia",     monto: 85,    categoria: "Salud",       fecha: "14 mar" },
      { id: "8", descripcion: "Restaurante",  monto: 95,    categoria: "Comida",      fecha: "12 mar" },
      { id: "9", descripcion: "Taxi",         monto: 35,    categoria: "Transporte",  fecha: "10 mar" },
      { id: "10", descripcion: "Cafeteria",   monto: 12,    categoria: "Comida",      fecha: "08 mar" },
    ],
    recomendaciones: [
      {
        id: "1",
        titulo: "Reducir gasto en comida",
        texto: "Considera reducir gastos de comida un 15%",
        fecha: "22 mar",
      },
      {
        id: "2",
        titulo: "Presupuesto de vivienda estable",
        texto: "Tu presupuesto de vivienda esta dentro del limite",
        fecha: "20 mar",
      },
    ],
    nuevaRecomendacionTitulo: "",
    nuevaRecomendacionTexto: "",
    showAllRecentExpenses: false,
  },
  perfil: {
    id: null,
    nombre: "",
    email: "",
    imagen: DEFAULT_PROFILE_IMAGE,
    passwordData: {
      actual: "",
      nueva: "",
      confirmar: "",
    },
    imagePreview: DEFAULT_PROFILE_IMAGE,
  },
  currentUser: null,
  profileLoaded: false,
  authRecovery: {
    email: "",
    codeVerified: false,
  },
  configuracion: {
    moneda: "USD",
    idioma: "es",
    tema: "system",
    temaOscuro: false,
    tamanioFuente: "md",
    densidad: "comfortable",
    reducirAnimaciones: false,
    mostrarCentavos: false,
    autenticacionDos: false,
    sesionesActivas: true,
    sesiones: [
      { id: 1, dispositivo: "Chrome - Windows", ubicacion: "Buenos Aires", fecha: "Hoy" },
      { id: 2, dispositivo: "Safari - iPhone",  ubicacion: "Buenos Aires", fecha: "Hace 2 dias" },
      { id: 3, dispositivo: "Chrome - Mac",     ubicacion: "Buenos Aires", fecha: "Hace 5 dias" },
    ],
    asesoria: {
      asesor: null,
      solicitud: {
        nombre: "",
        email: "",
        especialidad: "",
      },
    },
  },
  notificaciones: {
    resumenSemanal: true,
    alertaPago: true,
    alertaPresupuesto: true,
    movimientosGrandes: true,
    recomendacionesIA: true,
  },
};
